# Generated by Django 3.2.5 on 2021-07-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_auto',
        ),
        migrations.AddField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
    ]
