# Generated by Django 3.2.5 on 2021-07-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20210713_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='Property',
        ),
    ]
