# Generated by Django 3.2.5 on 2021-07-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='id',
            field=models.CharField(default='abctenant', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=45),
        ),
    ]
