# Generated by Django 3.2.5 on 2021-07-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20210714_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
    ]
