# Generated by Django 3.2.5 on 2021-07-14 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_remove_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_new',
            fields=[
                ('property_auto', models.AutoField(primary_key=True, serialize=False)),
                ('property_block', models.CharField(max_length=10)),
                ('property_name', models.CharField(max_length=45)),
                ('property_type', models.CharField(default='Residential', max_length=25)),
                ('property_category', models.CharField(default='Apartment buildings', max_length=35)),
                ('property_year', models.TextField(blank=True, null=True)),
                ('property_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_new',
            },
        ),
    ]
