# Generated by Django 3.2.5 on 2021-07-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_new',
        ),
    ]
