# Generated by Django 3.2.5 on 2021-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210714_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_auto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
