# Generated by Django 3.2.5 on 2021-07-14 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0013_property_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_buildings',
            fields=[
                ('property_auto', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=1)),
                ('property_block', models.CharField(max_length=10)),
                ('property_name', models.CharField(max_length=45)),
                ('property_type', models.CharField(default='Residential', max_length=25)),
                ('property_category', models.CharField(default='Apartment buildings', max_length=35)),
                ('property_year', models.TextField(blank=True, null=True)),
                ('property_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_buildings',
            },
        ),
        migrations.RemoveField(
            model_name='property_new',
            name='property_added_by',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Property_new',
        ),
    ]
